name: Integration tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run notebooks on treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          pip install -r requirements.txt -r requirements-dev.txt PySide2
      - name: Install package and extension
        run: |
          python -m pip install -e .
          jupyter nbextension install --py --symlink --sys-prefix itkwidgets
          jupyter nbextension enable --py --sys-prefix itkwidgets
          jupyter nbextension enable --py --sys-prefix widgetsnbextension
        env:
          MPLBACKEND: Qt5Agg
      - uses: treebeardtech/nbmake-action@v0.2.1
        with:
          docker-username: "${{ secrets.DOCKER_USERNAME }}"
          docker-password: "${{ secrets.DOCKER_PASSWORD }}"
          docker-image-name: insighttoolkit/itkwidgets
          notebooks: examples/*.ipynb
        env:
          MPLBACKEND: Qt5Agg
