name: Integration tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run notebooks on treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          pip install -r requirements.txt -r requirements-dev.txt PySide2
      - name: Install package and extension
        run: |
          python -m pip install -e .
          jupyter nbextension install --py --symlink --sys-prefix itkwidgets
          jupyter nbextension enable --py --sys-prefix itkwidgets
          jupyter nbextension enable --py --sys-prefix widgetsnbextension
        env:
          MPLBACKEND: Qt5Agg
      - uses: treebeardtech/nbmake-action@v0.2.1
        with:
          docker-username: "${{ secrets.DOCKER_USERNAME }}"
          docker-password: "${{ secrets.DOCKER_PASSWORD }}"
          docker-image-name: insighttoolkit/itkwidgets
          notebooks: |
            examples/2DImage.ipynb
            examples/3DImage.ipynb
            examples/CameraParameters.ipynb
            examples/Checkerboard.ipynb
            examples/CompareImages.ipynb
            examples/DaskArray.ipynb
            examples/ImageLabelStatistics.ipynb
            examples/ImageWithAnisotropicPixelSpacing.ipynb
            examples/InteractiveParameterExploration.ipynb
            examples/LabelImages.ipynb
            examples/LineProfile.ipynb
            examples/Mesh.ipynb
            examples/NumPyArrayImage.ipynb
            examples/NumPyArrayPointSet.ipynb
            examples/PointBasedSpatialObject.ipynb
            examples/pyvista.PolyData.ipynb
            examples/pyvista.PolyDataAndImageData.ipynb
            examples/pyvista.StructuredGrid.ipynb
            examples/pyvista.UniformGrid.ipynb
            examples/pyvista.UnstructuredGrid.ipynb
            examples/pyvistaLiDAR.ipynb
            examples/RecordAVideo.ipynb
            examples/scikit-image.ipynb
            examples/SegmentationSkeleton.ipynb
            examples/SelectRegionOfInterest.ipynb
            examples/SpecifyAColormap.ipynb
            examples/VolumeOpacityTransferFunction.ipynb
            examples/vtkImageData.ipynb
            examples/vtkPolyData.ipynb
            examples/vtkUnstructuredGrid.ipynb
        env:
          MPLBACKEND: Qt5Agg
