name: Integration tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run notebooks on treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: treebeardtech/nbmake-action@v0.2.1
        with:
          docker-username: "${{ secrets.DOCKER_USERNAME }}"
          docker-password: "${{ secrets.DOCKER_PASSWORD }}"
          docker-image-name: insighttoolkit/itkwidgets
          notebooks: examples/*.ipynb
